
import { Product } from "@/types";

// Mock product data
export const products: Product[] = [
  {
    id: "prod_1",
    name: "Essential Oversized Tee",
    description: "Crafted from premium cotton, this oversized tee offers unmatched comfort with a modern silhouette. Perfect for layering or as a standalone statement piece.",
    price: 229900,
    originalPrice: 299900,
    category: "t-shirts",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    variants: [
      { id: "var_1", size: "XS", color: "Black", colorCode: "#000000", stock: 10 },
      { id: "var_2", size: "S", color: "Black", colorCode: "#000000", stock: 15 },
      { id: "var_3", size: "M", color: "Black", colorCode: "#000000", stock: 20 },
      { id: "var_4", size: "L", color: "Black", colorCode: "#000000", stock: 20 },
      { id: "var_5", size: "XL", color: "Black", colorCode: "#000000", stock: 10 },
      { id: "var_6", size: "XS", color: "White", colorCode: "#FFFFFF", stock: 10 },
      { id: "var_7", size: "S", color: "White", colorCode: "#FFFFFF", stock: 15 },
      { id: "var_8", size: "M", color: "White", colorCode: "#FFFFFF", stock: 20 },
      { id: "var_9", size: "L", color: "White", colorCode: "#FFFFFF", stock: 20 },
      { id: "var_10", size: "XL", color: "White", colorCode: "#FFFFFF", stock: 10 },
      { id: "var_11", size: "XS", color: "Navy", colorCode: "#000080", stock: 10 },
      { id: "var_12", size: "S", color: "Navy", colorCode: "#000080", stock: 15 },
      { id: "var_13", size: "M", color: "Navy", colorCode: "#000080", stock: 20 },
      { id: "var_14", size: "L", color: "Navy", colorCode: "#000080", stock: 20 },
      { id: "var_15", size: "XL", color: "Navy", colorCode: "#000080", stock: 10 },
      { id: "var_16", size: "XS", color: "Olive", colorCode: "#556B2F", stock: 10 },
      { id: "var_17", size: "S", color: "Olive", colorCode: "#556B2F", stock: 15 },
      { id: "var_18", size: "M", color: "Olive", colorCode: "#556B2F", stock: 20 },
      { id: "var_19", size: "L", color: "Olive", colorCode: "#556B2F", stock: 20 },
      { id: "var_20", size: "XL", color: "Olive", colorCode: "#556B2F", stock: 10 },
    ],
    featured: true,
    rating: 4.8,
    reviews: 124,
    inStock: true,
  },
  {
    id: "prod_2",
    name: "Urban Cargo Pants",
    description: "These cargo pants combine streetwear aesthetics with practical design. Multiple pockets and adjustable features offer both style and functionality.",
    price: 399900,
    category: "pants",
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582552938357-32b906df40cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    variants: [
      { id: "var_21", size: "XS", color: "Olive", colorCode: "#556B2F", stock: 8 },
      { id: "var_22", size: "S", color: "Olive", colorCode: "#556B2F", stock: 12 },
      { id: "var_23", size: "M", color: "Olive", colorCode: "#556B2F", stock: 15 },
      { id: "var_24", size: "L", color: "Olive", colorCode: "#556B2F", stock: 15 },
      { id: "var_25", size: "XL", color: "Olive", colorCode: "#556B2F", stock: 6 },
      { id: "var_26", size: "XS", color: "Black", colorCode: "#000000", stock: 8 },
      { id: "var_27", size: "S", color: "Black", colorCode: "#000000", stock: 12 },
      { id: "var_28", size: "M", color: "Black", colorCode: "#000000", stock: 15 },
      { id: "var_29", size: "L", color: "Black", colorCode: "#000000", stock: 15 },
      { id: "var_30", size: "XL", color: "Black", colorCode: "#000000", stock: 6 },
      { id: "var_31", size: "XS", color: "Beige", colorCode: "#F5F5DC", stock: 8 },
      { id: "var_32", size: "S", color: "Beige", colorCode: "#F5F5DC", stock: 12 },
      { id: "var_33", size: "M", color: "Beige", colorCode: "#F5F5DC", stock: 15 },
      { id: "var_34", size: "L", color: "Beige", colorCode: "#F5F5DC", stock: 15 },
      { id: "var_35", size: "XL", color: "Beige", colorCode: "#F5F5DC", stock: 6 },
      { id: "var_36", size: "XS", color: "Gray", colorCode: "#808080", stock: 8 },
      { id: "var_37", size: "S", color: "Gray", colorCode: "#808080", stock: 12 },
      { id: "var_38", size: "M", color: "Gray", colorCode: "#808080", stock: 15 },
      { id: "var_39", size: "L", color: "Gray", colorCode: "#808080", stock: 15 },
      { id: "var_40", size: "XL", color: "Gray", colorCode: "#808080", stock: 6 },
    ],
    featured: true,
    rating: 4.5,
    reviews: 86,
    inStock: true,
  },
  {
    id: "prod_3",
    name: "Logo Hoodie",
    description: "Stay warm in style with our signature hoodie. Made from heavyweight cotton blend with a brushed interior for maximum comfort and warmth.",
    price: 499900,
    category: "hoodies",
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1565693413579-8a218c23d3c5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    variants: [
      { id: "var_41", size: "XS", color: "Black", colorCode: "#000000", stock: 12 },
      { id: "var_42", size: "S", color: "Black", colorCode: "#000000", stock: 18 },
      { id: "var_43", size: "M", color: "Black", colorCode: "#000000", stock: 22 },
      { id: "var_44", size: "L", color: "Black", colorCode: "#000000", stock: 22 },
      { id: "var_45", size: "XL", color: "Black", colorCode: "#000000", stock: 15 },
      { id: "var_46", size: "XS", color: "Gray", colorCode: "#808080", stock: 10 },
      { id: "var_47", size: "S", color: "Gray", colorCode: "#808080", stock: 16 },
      { id: "var_48", size: "M", color: "Gray", colorCode: "#808080", stock: 20 },
      { id: "var_49", size: "L", color: "Gray", colorCode: "#808080", stock: 20 },
      { id: "var_50", size: "XL", color: "Gray", colorCode: "#808080", stock: 12 },
      { id: "var_51", size: "XS", color: "Navy", colorCode: "#000080", stock: 10 },
      { id: "var_52", size: "S", color: "Navy", colorCode: "#000080", stock: 16 },
      { id: "var_53", size: "M", color: "Navy", colorCode: "#000080", stock: 20 },
      { id: "var_54", size: "L", color: "Navy", colorCode: "#000080", stock: 20 },
      { id: "var_55", size: "XL", color: "Navy", colorCode: "#000080", stock: 12 },
      { id: "var_56", size: "XS", color: "Burgundy", colorCode: "#800020", stock: 10 },
      { id: "var_57", size: "S", color: "Burgundy", colorCode: "#800020", stock: 16 },
      { id: "var_58", size: "M", color: "Burgundy", colorCode: "#800020", stock: 20 },
      { id: "var_59", size: "L", color: "Burgundy", colorCode: "#800020", stock: 20 },
      { id: "var_60", size: "XL", color: "Burgundy", colorCode: "#800020", stock: 12 },
    ],
    featured: true,
    rating: 4.9,
    reviews: 215,
    inStock: true,
  },
  {
    id: "prod_4",
    name: "Technical Jacket",
    description: "Our Technical Jacket combines weather resistance with urban styling. Multiple pockets and adjustable features make it both practical and fashionable.",
    price: 799900,
    originalPrice: 999900,
    category: "jackets",
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1577660002965-04865592fc60?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    variants: [
      { id: "var_61", size: "XS", color: "Black", colorCode: "#000000", stock: 6 },
      { id: "var_62", size: "S", color: "Black", colorCode: "#000000", stock: 10 },
      { id: "var_63", size: "M", color: "Black", colorCode: "#000000", stock: 8 },
      { id: "var_64", size: "L", color: "Black", colorCode: "#000000", stock: 8 },
      { id: "var_65", size: "XL", color: "Black", colorCode: "#000000", stock: 4 },
      { id: "var_66", size: "XS", color: "Olive", colorCode: "#556B2F", stock: 6 },
      { id: "var_67", size: "S", color: "Olive", colorCode: "#556B2F", stock: 10 },
      { id: "var_68", size: "M", color: "Olive", colorCode: "#556B2F", stock: 8 },
      { id: "var_69", size: "L", color: "Olive", colorCode: "#556B2F", stock: 8 },
      { id: "var_70", size: "XL", color: "Olive", colorCode: "#556B2F", stock: 4 },
      { id: "var_71", size: "XS", color: "Navy", colorCode: "#000080", stock: 6 },
      { id: "var_72", size: "S", color: "Navy", colorCode: "#000080", stock: 10 },
      { id: "var_73", size: "M", color: "Navy", colorCode: "#000080", stock: 8 },
      { id: "var_74", size: "L", color: "Navy", colorCode: "#000080", stock: 8 },
      { id: "var_75", size: "XL", color: "Navy", colorCode: "#000080", stock: 4 },
      { id: "var_76", size: "XS", color: "Burgundy", colorCode: "#800020", stock: 6 },
      { id: "var_77", size: "S", color: "Burgundy", colorCode: "#800020", stock: 10 },
      { id: "var_78", size: "M", color: "Burgundy", colorCode: "#800020", stock: 8 },
      { id: "var_79", size: "L", color: "Burgundy", colorCode: "#800020", stock: 8 },
      { id: "var_80", size: "XL", color: "Burgundy", colorCode: "#800020", stock: 4 },
    ],
    featured: true,
    rating: 4.7,
    reviews: 58,
    inStock: true,
  },
  {
    id: "prod_5",
    name: "Minimalist Shorts",
    description: "Clean lines and premium materials define our Minimalist Shorts. Perfect for warm weather with a comfortable fit and subtle branded details.",
    price: 299900,
    category: "shorts",
    images: [
      "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    variants: [
      { id: "var_81", size: "XS", color: "Black", colorCode: "#000000", stock: 20 },
      { id: "var_82", size: "S", color: "Black", colorCode: "#000000", stock: 25 },
      { id: "var_83", size: "M", color: "Black", colorCode: "#000000", stock: 25 },
      { id: "var_84", size: "L", color: "Black", colorCode: "#000000", stock: 25 },
      { id: "var_85", size: "XL", color: "Black", colorCode: "#000000", stock: 15 },
      { id: "var_86", size: "XS", color: "Beige", colorCode: "#F5F5DC", stock: 18 },
      { id: "var_87", size: "S", color: "Beige", colorCode: "#F5F5DC", stock: 22 },
      { id: "var_88", size: "M", color: "Beige", colorCode: "#F5F5DC", stock: 22 },
      { id: "var_89", size: "L", color: "Beige", colorCode: "#F5F5DC", stock: 22 },
      { id: "var_90", size: "XL", color: "Beige", colorCode: "#F5F5DC", stock: 12 },
      { id: "var_91", size: "XS", color: "Navy", colorCode: "#000080", stock: 18 },
      { id: "var_92", size: "S", color: "Navy", colorCode: "#000080", stock: 22 },
      { id: "var_93", size: "M", color: "Navy", colorCode: "#000080", stock: 22 },
      { id: "var_94", size: "L", color: "Navy", colorCode: "#000080", stock: 22 },
      { id: "var_95", size: "XL", color: "Navy", colorCode: "#000080", stock: 12 },
      { id: "var_96", size: "XS", color: "Olive", colorCode: "#556B2F", stock: 18 },
      { id: "var_97", size: "S", color: "Olive", colorCode: "#556B2F", stock: 22 },
      { id: "var_98", size: "M", color: "Olive", colorCode: "#556B2F", stock: 22 },
      { id: "var_99", size: "L", color: "Olive", colorCode: "#556B2F", stock: 22 },
      { id: "var_100", size: "XL", color: "Olive", colorCode: "#556B2F", stock: 12 },
    ],
    featured: true,
    rating: 4.6,
    reviews: 92,
    inStock: true,
  },
  {
    id: "prod_6",
    name: "Logo Cap",
    description: "Complete your look with our signature cap featuring embroidered logo details. One size fits most with an adjustable strap.",
    price: 199900,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    variants: [
      { id: "var_101", size: "One Size", color: "Black", colorCode: "#000000", stock: 30 },
      { id: "var_102", size: "One Size", color: "White", colorCode: "#FFFFFF", stock: 25 },
      { id: "var_103", size: "One Size", color: "Navy", colorCode: "#000080", stock: 30 },
      { id: "var_104", size: "One Size", color: "Olive", colorCode: "#556B2F", stock: 25 },
    ],
    featured: false,
    rating: 4.8,
    reviews: 76,
    inStock: true,
  },
];

// Categories for navigation
export const categories = [
  { id: "cat_1", name: "T-Shirts", slug: "t-shirts" },
  { id: "cat_2", name: "Hoodies", slug: "hoodies" },
  { id: "cat_3", name: "Pants", slug: "pants" },
  { id: "cat_4", name: "Shorts", slug: "shorts" },
  { id: "cat_5", name: "Jackets", slug: "jackets" },
  { id: "cat_6", name: "Accessories", slug: "accessories" },
];

// Sample user for testing authentication
export const sampleUser = {
  id: "user_1",
  email: "user@test.com",
  name: "Test User",
  role: "user" as const
};

// Sample admin for testing authentication
export const sampleAdmin = {
  id: "admin_1",
  email: "admin@test.com",
  name: "Admin User",
  role: "admin" as const
};
